[profile.default]
solc = '0.8.21'
evm_version = 'paris'
via_ir = true
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
optimizer = true
optimizer_runs = 10_000_000

[fuzz]
runs = 5000

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
bsc = "${BSC_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}", chain = 42161 }
base = { key = "${BASESCAN_API_KEY}", chain = 8453 }
bsc = { key = "${BSCSCAN_API_KEY}", chain = 56 }
ethereum = { key = "${ETHERSCAN_API_KEY}", chain = 137 }
optimism = { key = "${OPTIMISMSCAN_API_KEY}", chain = 10 }
polygon = { key = "${POLYGONSCAN_API_KEY}", chain = 137 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
